### ISSUE TITLE
Does not work with changed project root

### ISSUE THREAD

**Issue by wvffle** [dishait/vite-auto-import-resolvers#1]
When I change the [`root`](https://vitejs.dev/config/#root) config the composables are not resolved at all

**Comment by markthree** [comment]
hello， @wvffle, Because I only made the directory under `src`，Maybe it can have a more reasonable path processing, but I'm doing other work at present. If you have good suggestions, welcome PR

**Comment by markthree** [comment]
hello, @wvffle the `root` option is supported now，you can look [README_EN.md#root](https://github.com/dishait/vite-auto-import-resolvers/blob/main/README_EN.md#root)，and Update version ^2.2.1
