### ISSUE TITLE
自动导入自定义的api，能不能支持根据 resolve.alias 定义路径前缀，而不是本地的文件路径

### ISSUE THREAD

**Issue by 316374157** [dishait/vite-auto-import-resolvers#5]
以仓库中的例子来说就是，
auto-imports.d.ts文件中的
 const bar: typeof import('/Code/Work/vite-auto-import-resolvers/examples/vue/shared/bar')['default']
能不能生成成类似下面这种形式的：
 const bar: typeof import('@/vue/shared/bar')['default'] 或者
 const bar: typeof import('~/vue/shared/bar')['default']
![image](https://user-images.githubusercontent.com/46001074/166624593-ea8e0d34-91af-429c-974b-b9bca8e1d48d.png)

**Comment by markthree** [comment]
靓仔你好，支持过的，但是这需要让用户需要手动设置类型声明

**Comment by markthree** [comment]
如果你有更好的方案也欢迎 `pr`

**Comment by 316374157** [comment]
手动设置是改生成文件还是在配置文件中配置呢？是root这个配置吗

**Comment by markthree** [comment]
@316374157 可以看废弃的 `api` 以及过往的提交记录，不过因为是废弃的了 `api`，所以目前是不起效果的

**Comment by 316374157** [comment]
好的

**Comment by markthree** [comment]
@316374157 已开放 [规范路径](https://github.com/dishait/vite-auto-import-resolvers#%E8%A7%84%E8%8C%83%E8%B7%AF%E5%BE%84)，可以自定义为你想要的正确路径
