### ISSUE TITLE
在使用vite3版本的时候，会出现Dynamic require of "path" is not supported的错误

### ISSUE THREAD

**Issue by xuxilan** [dishait/vite-auto-import-resolvers#8]
![image](https://user-images.githubusercontent.com/66450680/200100661-fe49faf4-5c71-48d9-9d0d-701d1c197eb3.png)
`failed to load config from E:\Project\Vue3\xl-xling-admin\vite.config.ts
error when starting dev server:
Error: Dynamic require of "path" is not supported
    at file:///E:/Project/Vue3/xl-xling-admin/node_modules/.pnpm/vite-auto-import-resolvers@3.0.1_v5xq3qlwvf4akn2un7a5tsc4oq/node_modules/vite-auto-import-resolvers/dist/index.mjs:1:775
    at file:///E:/Project/Vue3/xl-xling-admin/node_modules/.pnpm/vite-auto-import-resolvers@3.0.1_v5xq3qlwvf4akn2un7a5tsc4oq/node_modules/vite-auto-import-resolvers/dist/index.mjs:1:2352
    at file:///E:/Project/Vue3/xl-xling-admin/node_modules/.pnpm/vite-auto-import-resolvers@3.0.1_v5xq3qlwvf4akn2un7a5tsc4oq/node_modules/vite-auto-import-resolvers/dist/index.mjs:1:891
    at file:///E:/Project/Vue3/xl-xling-admin/node_modules/.pnpm/vite-auto-import-resolvers@3.0.1_v5xq3qlwvf4akn2un7a5tsc4oq/node_modules/vite-auto-import-resolvers/dist/index.mjs:2:32192
    at file:///E:/Project/Vue3/xl-xling-admin/node_modules/.pnpm/vite-auto-import-resolvers@3.0.1_v5xq3qlwvf4akn2un7a5tsc4oq/node_modules/vite-auto-import-resolvers/dist/index.mjs:1:891
    at file:///E:/Project/Vue3/xl-xling-admin/node_modules/.pnpm/vite-auto-import-resolvers@3.0.1_v5xq3qlwvf4akn2un7a5tsc4oq/node_modules/vite-auto-import-resolvers/dist/index.mjs:2:32554
    at file:///E:/Project/Vue3/xl-xling-admin/node_modules/.pnpm/vite-auto-import-resolvers@3.0.1_v5xq3qlwvf4akn2un7a5tsc4oq/node_modules/vite-auto-import-resolvers/dist/index.mjs:1:891
    at file:///E:/Project/Vue3/xl-xling-admin/node_modules/.pnpm/vite-auto-import-resolvers@3.0.1_v5xq3qlwvf4akn2un7a5tsc4oq/node_modules/vite-auto-import-resolvers/dist/index.mjs:2:61536
    at file:///E:/Project/Vue3/xl-xling-admin/node_modules/.pnpm/vite-auto-import-resolvers@3.0.1_v5xq3qlwvf4akn2un7a5tsc4oq/node_modules/vite-auto-import-resolvers/dist/index.mjs:1:891
    at file:///E:/Project/Vue3/xl-xling-admin/node_modules/.pnpm/vite-auto-import-resolvers@3.0.1_v5xq3qlwvf4akn2un7a5tsc4oq/node_modules/vite-auto-import-resolvers/dist/index.mjs:2:65541
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by markthree** [comment]
@XAllure 靓仔你好，已确认 `bug`，请等待修复

**Comment by markthree** [comment]
@XAllure 靓仔你好，已更新，请更新版本到 `^3.0.3`。具体变动可见 👉 [releases/tag/v3.0.3](https://github.com/dishait/vite-auto-import-resolvers/releases/tag/v3.0.3)

**Comment by xuxilan** [comment]
> @XAllure 靓仔你好，已更新，请更新版本到 `^3.0.3`。具体变动可见 👉 [releases/tag/v3.0.3](https://github.com/dishait/vite-auto-import-resolvers/releases/tag/v3.0.3)

OK，感谢修复！
